# -*- coding: utf-8 -*-
"""Codigo_para_despliegue_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WEbM4M7BGTtHqNQJe8gYRASYrIlHt8g
"""

import streamlit as st
import pandas as pd
import re

st.title("Procesador de Materiales SAP")

archivo = st.file_uploader("Sube tu archivo de materiales (.xlsx)", type="xlsx")

if archivo:
    df = pd.read_excel(archivo)

    # === Normalizar Ubicación (evita error en min/max) ===
    df['Ubicación'] = df['Ubicación'].fillna("").astype(str)

    # === Funciones auxiliares para min y max ignorando vacíos ===
    def min_no_vacio(series):
        vals = [v for v in series if v != ""]
        return min(vals) if vals else ""

    def max_no_vacio(series):
        vals = [v for v in series if v != ""]
        return max(vals) if vals else ""

    # === Función para separar número y unidad ===
    def separar_numero_unidad(valor):
        if pd.isna(valor):
            return 0.0, ""
        valor = str(valor).strip()
        match = re.match(r"([\d\.,]+)\s*(\w+)?", valor)
        if match:
            numero = match.group(1).replace(".", "").replace(",", ".")
            unidad = match.group(2) if match.group(2) else ""
            try:
                return float(numero), unidad
            except:
                return 0.0, unidad
        return 0.0, ""

    # === Aplicar la función a las columnas de stock ===
    df[['Stock_libre','Unidad_libre']] = df['Stock de libre utilización'].apply(lambda x: pd.Series(separar_numero_unidad(x)))
    df[['Stock_bloqueado','Unidad_bloqueado']] = df['Stock bloqueado'].apply(lambda x: pd.Series(separar_numero_unidad(x)))

    # === Agrupación Stock Regular (Vacíos) ===
    df_vacio = df[df['Tipo de stock especial'].isna()]
    res_vacio = df_vacio.groupby(['Centro','Almacén']).agg(
        Cantidad=('Material','size'),
        Stock_libre=('Stock_libre','sum'),
        Stock_bloqueado=('Stock_bloqueado','sum'),
        Valor_libre=('Valor de stock de libre utilización','sum'),
        Valor_bloqueado=('Valor actual de stock bloqueado','sum'),
        Ubicacion_desde=('Ubicación', min_no_vacio),
        Ubicacion_hasta=('Ubicación', max_no_vacio)
    ).reset_index()

    # === Agrupación Q con PEP ===
    df_q = df[df['Tipo de stock especial'] == 'Q']
    res_pep_q = df_q.groupby(['Centro','Almacén','Elemento PEP']).agg(
        Cantidad=('Material','size'),
        Stock_libre=('Stock_libre','sum'),
        Stock_bloqueado=('Stock_bloqueado','sum'),
        Valor_libre=('Valor de stock de libre utilización','sum'),
        Valor_bloqueado=('Valor actual de stock bloqueado','sum'),
        Ubicacion_desde=('Ubicación', min_no_vacio),
        Ubicacion_hasta=('Ubicación', max_no_vacio)
    ).reset_index()

    # === Formato de pesos y decimales ===
    def formato_pesos(x):
        return "${:,.2f}".format(x)

    for df_out in [res_vacio, res_pep_q]:
        df_out['Stock_libre'] = df_out['Stock_libre'].round(2)
        df_out['Stock_bloqueado'] = df_out['Stock_bloqueado'].round(2)
        df_out['Valor_libre'] = df_out['Valor_libre'].apply(formato_pesos)
        df_out['Valor_bloqueado'] = df_out['Valor_bloqueado'].apply(formato_pesos)

    # === Totales con rango global ===
    totales_vacio = pd.DataFrame({
        'Centro': ['TOTAL'],
        'Almacén': [''],
        'Cantidad': [df_vacio['Material'].count()],
        'Stock_libre': [round(df_vacio['Stock_libre'].sum(),2)],
        'Stock_bloqueado': [round(df_vacio['Stock_bloqueado'].sum(),2)],
        'Valor_libre': [formato_pesos(df_vacio['Valor de stock de libre utilización'].sum())],
        'Valor_bloqueado': [formato_pesos(df_vacio['Valor actual de stock bloqueado'].sum())],
        'Ubicacion_desde': [min_no_vacio(df_vacio['Ubicación'])],
        'Ubicacion_hasta': [max_no_vacio(df_vacio['Ubicación'])]
    })

    totales_pep_q = pd.DataFrame({
        'Centro': ['TOTAL'],
        'Almacén': [''],
        'Elemento PEP': [''],
        'Cantidad': [df_q['Material'].count()],
        'Stock_libre': [round(df_q['Stock_libre'].sum(),2)],
        'Stock_bloqueado': [round(df_q['Stock_bloqueado'].sum(),2)],
        'Valor_libre': [formato_pesos(df_q['Valor de stock de libre utilización'].sum())],
        'Valor_bloqueado': [formato_pesos(df_q['Valor actual de stock bloqueado'].sum())],
        'Ubicacion_desde': [min_no_vacio(df_q['Ubicación'])],
        'Ubicacion_hasta': [max_no_vacio(df_q['Ubicación'])]
    })

    # Índice Doc 1, Doc 2... y TOTAL sin índice
    res_vacio.index = [f"Doc {i+1}" for i in range(len(res_vacio))]
    res_pep_q.index = [f"Doc {i+1}" for i in range(len(res_pep_q))]

    res_vacio = pd.concat([res_vacio, totales_vacio], axis=0)
    res_pep_q = pd.concat([res_pep_q, totales_pep_q], axis=0)

    res_vacio.index = list(res_vacio.index[:-1]) + ['TOTAL']
    res_pep_q.index = list(res_pep_q.index[:-1]) + ['TOTAL']

    # === Mostrar tablas con títulos personalizados ===
    st.markdown("## **Material en Stock Regular (PSE, POR)**")
    st.markdown("**<span style='font-size:14px'>Creación de documento de inventario mediante MI31</span>**", unsafe_allow_html=True)
    st.dataframe(res_vacio)

    st.markdown("## **Material de Proyectos por Elemento PEP**")
    st.markdown("**<span style='font-size:14px'>Creación de documento de inventario mediante MI01</span>**", unsafe_allow_html=True)
    st.dataframe(res_pep_q)

    # === Exportar Excel con todas las columnas por Elemento PEP ===
    def limpiar_nombre(nombre):
        return re.sub(r'[\[\]:\*\/\\\?]', '_', str(nombre))[:31]

    # Ordenar primero por Ubicación y luego por Material (NaN al final)
    df_q = df_q.sort_values(by=['Ubicación','Material'], ascending=[True, True], na_position='last')

    nombre_salida = "Materiales_Por_Elemento_PEP.xlsx"
    with pd.ExcelWriter(nombre_salida, engine="openpyxl") as writer:
        for pep, grupo in df_q.groupby("Elemento PEP"):
            grupo.to_excel(writer, sheet_name=limpiar_nombre(pep), index=False)

    with open(nombre_salida, "rb") as f:
        st.download_button("📥 Descargar Excel", f, file_name=nombre_salida)