# -*- coding: utf-8 -*-
"""Procesador Materiales Para Despliegue Streamlit V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBodX_UK7cAJGmQ3aDvIcAda7nCw6gll
"""

import streamlit as st
import pandas as pd
import re
from io import BytesIO

# === Configuración de la página ===
st.set_page_config(
    page_title="Procesador de Materiales Inventario Físico SAP Almacenes EPM",
    page_icon="📦",
    layout="wide"
)

st.title("📦 Procesador de Materiales Inventario Físico SAP Almacenes EPM")
st.markdown(
    """
    Esta aplicación permite cargar un archivo Excel exportado desde SAP (Stock Varios Materiales),
    identificar y determinar información para generación de actas y documentos de inventario físico en las diferentes transacciones y exportar un archivo con los materiales de
    **Stock especial Q (Proyectos)**, separados por **Elemento PEP**,
    ordenados por **Ubicación**, para facilitar la creación de los documentos de inventario mediante transacción MI01 por material individual
    """
)

# === Subir archivo Excel ===
archivo = st.file_uploader("📂 Subir archivo Excel de materiales SAP", type=["xlsx"])

if archivo is not None:
    df = pd.read_excel(archivo)

    # Normalizar columnas
    df['Ubicación'] = df['Ubicación'].fillna("").astype(str)
    df['Tipo de stock especial'] = df['Tipo de stock especial'].fillna("")

    # Conversión de números con miles "." y decimales ","
    def convertir_numero(valor):
        if pd.isna(valor):
            return 0.0
        valor = str(valor).strip()
        # quitar puntos de miles y cambiar coma por punto decimal
        valor = valor.replace(".", "").replace(",", ".")
        try:
            return float(valor)
        except:
            return 0.0

    # Convertir columnas numéricas
    df['Stock_libre_num'] = df['Stock de libre utilización'].apply(convertir_numero)
    df['Stock_bloqueado_num'] = df['Stock bloqueado'].apply(convertir_numero)
    df['Valor_libre_num'] = df['Valor de stock de libre utilización'].apply(convertir_numero)
    df['Valor_bloqueado_num'] = df['Valor actual de stock bloqueado'].apply(convertir_numero)

    # === Validación ===
    df_invalidos = df[~df['Tipo de stock especial'].isin(["","Q"])]
    st.subheader("⚠️ Validación de materiales con imputación diferente a vacío y Q)")
    if not df_invalidos.empty:
        st.dataframe(df_invalidos[['Centro','Almacén','Descripción de almacén','Tipo de stock especial','Material']])
    else:
        st.dataframe(pd.DataFrame([{
            'Centro': '0','Almacén': '0','Descripción de almacén': '0','Tipo de stock especial': '0','Material': '0'
        }]))

    # === Mostrar Actas ===
    st.subheader("📊 Desarrollo de Actas de Inventario")
    contador_acta = 1
    mapa_titulos = {"": "Material en Stock Regular", "Q": "Material de Proyectos"}
    frases = {"": "Creación de documento de inventario físico mediante transacción MI31",
              "Q": "Creación de documento de inventario físico mediante transacción MI01"}

    for tipo in ["", "Q"]:
        df_tipo = df[df['Tipo de stock especial'] == tipo]
        for almacen, grupo in df_tipo.groupby('Almacén'):
            desc_almacen = grupo['Descripción de almacén'].iloc[0]
            nombre_acta = f"Acta {contador_acta} – {mapa_titulos[tipo]} | Almacén {almacen} ({desc_almacen})"
            contador_acta += 1

            claves = ['Centro'] + (['Elemento PEP'] if tipo=="Q" else [])
            resumen = grupo.groupby(claves).agg(
                Cantidad=('Material','size'),
                Stock_libre=('Stock_libre_num','sum'),
                Stock_bloqueado=('Stock_bloqueado_num','sum'),
                Valor_libre=('Valor_libre_num','sum'),
                Valor_bloqueado=('Valor_bloqueado_num','sum'),
                Ubicacion_desde=('Ubicación', lambda x: min([v for v in x if v != ""], default="")),
                Ubicacion_hasta=('Ubicación', lambda x: max([v for v in x if v != ""], default="")),
                Ubicaciones_vacias=('Ubicación', lambda x: (x=="").sum())
            ).reset_index()

            # Índice Doc 1, Doc 2...
            resumen.index = [f'Doc {i+1}' for i in range(len(resumen))]

            # Insertar columnas al lado de Centro
            resumen.insert(1, 'Almacén', almacen)
            resumen.insert(2, 'Descripción de almacén', desc_almacen)
            resumen.insert(3, 'Tipo de stock especial', "Vacío" if tipo=="" else "Q")

            # Crear fila TOTAL
            fila_total = {
                'Centro': 'TOTAL',
                'Almacén': almacen,
                'Descripción de almacén': desc_almacen,
                'Tipo de stock especial': "Vacío" if tipo=="" else "Q",
                'Cantidad': resumen['Cantidad'].sum(),
                'Stock_libre': resumen['Stock_libre'].sum(),
                'Stock_bloqueado': resumen['Stock_bloqueado'].sum(),
                'Valor_libre': resumen['Valor_libre'].sum(),
                'Valor_bloqueado': resumen['Valor_bloqueado'].sum(),
                'Ubicacion_desde': resumen['Ubicacion_desde'].min(),
                'Ubicacion_hasta': resumen['Ubicacion_hasta'].max(),
                'Ubicaciones_vacias': resumen['Ubicaciones_vacias'].sum()
            }
            resumen.loc['TOTAL'] = fila_total

            # Mostrar Acta
            st.markdown(f"### {nombre_acta}")
            st.markdown(f"**{frases[tipo]}**")
            st.dataframe(resumen.style.format({
                'Stock_libre': '{:.2f}',
                'Stock_bloqueado': '{:.2f}',
                'Valor_libre': '${:,.2f}',
                'Valor_bloqueado': '${:,.2f}'
            }))

    # === Exportar Excel con hojas por Elemento PEP (solo Stock especial Q) ===
    st.subheader("💾 Exportar Excel Material Proyectos por Elemento PEP")
    for almacen, grupo in df[df['Tipo de stock especial'] == "Q"].groupby('Almacén'):
        nombre_archivo = f"Materiales_Por_Elemento_PEP_{almacen}.xlsx"
        output = BytesIO()

        with pd.ExcelWriter(output, engine="openpyxl") as writer:
            for pep, subgrupo in grupo.groupby("Elemento PEP"):
                subgrupo_ordenado = subgrupo.sort_values(by=['Ubicación','Material'], ascending=[True, True])
                nombre_hoja = re.sub(r'[\[\]\\/:*?"<>|]', '-', str(pep))[:31]
                subgrupo_ordenado.to_excel(writer, sheet_name=nombre_hoja, index=False)

        st.download_button(
            label=f"⬇️ Descargar Excel para Almacén {almacen}",
            data=output.getvalue(),
            file_name=nombre_archivo,
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
